# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Goat_Challenge' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Goat_Challenge
  pod 'SnapKit'
  pod 'Alamofire'
  pod 'AlamofireImage'

  target 'Goat_ChallengeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Goat_ChallengeUITests' do
    # Pods for testing
  end

end
